# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 16:21
from __future__ import unicode_literals
import datetime
import YAAS.models
from django.db import migrations, models
from django.utils.timezone import utc



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.CharField(default=YAAS.models.make_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('owner', models.CharField(default=YAAS.models.make_uuid, max_length=36)),
                ('seller', models.CharField(default='username', max_length=30)),
                ('title', models.TextField(max_length=40)),
                ('description', models.TextField(max_length=10000)),
                ('current_bid', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2016, 11, 5, 16, 21, 22, 371000, tzinfo=utc))),
                ('top_bidder', models.CharField(default=YAAS.models.make_uuid, max_length=36)),
                ('banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.CharField(default=YAAS.models.make_uuid, max_length=36, primary_key=True, serialize=False)),
                ('auction_id', models.CharField(max_length=36)),
                ('bidder', models.CharField(max_length=30)),
                ('bid', models.IntegerField(default=80085)),
            ],
        ),
    ]
