# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS', '0002_auto_20161106_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 19, 33, 33, 425000, tzinfo=utc)),
        ),
    ]
