# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS', '0003_auto_20161106_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 19, 41, 3, 772000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=8),
        ),
    ]
